export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";
export const MOVIE_FAILURE = "MOVIE_FAILURE";
export const UPDATE_RATING = "UPDATE_RATING";
export const UPDATE_ORDER = "UPDATE_ORDER";
